name: Build Python Executable for x86_64 and aarch64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04  # 默认使用 x86_64 运行环境

    strategy:
      matrix:
        architecture: [x86_64, aarch64]  # 在 x86_64 和 aarch64 上构建

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 选择你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # 安装 PyInstaller
          pip install poetry


      - name: Set up cross-compilation (for aarch64)
        if: matrix.architecture == 'aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static  # 安装 QEMU 以支持跨架构编译
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
      - name: Build for x86_64 or aarch64
        run: |
          # 使用 PyInstaller 打包 Python 程序
          if [[ "${{ matrix.architecture }}" == "aarch64" ]]; then
            # 为 aarch64 架构打包
            poetry install
            pyinstaller --onefile --name payload_dumper_aarch64 src/payload_dumper/__main__.py
          else
            # 为 x86_64 架构打包
            poetry install
            pyinstaller --onefile --name payload_dumper_x86_64 src/payload_dumper/__main__.py
          fi

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-executables
          path: dist/  # PyInstaller 默认将文件输出到 dist 目录

